### ISSUE TITLE
the release of a trained BERT+Voken-cls model

### ISSUE THREAD

**Issue by mrzhang11** [airsplay/vokenization#1]
Hi,

the work is so interesting.  I was wondering that if you have a plan to release a trained BERT+Voken-cls model?

Thanks!

**Comment by airsplay** [comment]
Sure! Here it is: [http://nlp.cs.unc.edu/data/vokenization/vlm_12L_768H_wiki.zip](http://nlp.cs.unc.edu/data/vokenization/vlm_12L_768H_wiki.zip).

**Comment by mrzhang11** [comment]
Thanks for the quick reply!!

Would u mind also release the trained BERT_12L_768H_wiki baseline for fair comparison?

**Comment by airsplay** [comment]
Sure, here: [http://nlp.cs.unc.edu/data/vokenization/bert_12L_768H_wiki.zip](http://nlp.cs.unc.edu/data/vokenization/bert_12L_768H_wiki.zip).

**Comment by mrzhang11** [comment]
Thanks!
