### ISSUE TITLE
Question: Tokenizer used for RoBERTa model?

### ISSUE THREAD

**Issue by FelixLabelle** [airsplay/vokenization#4]
I'm [trying to integrate Vokenization with BERTScore](https://github.com/Tiiiger/bert_score/issues/95) and I'd like to get clarification on which tokenizer is being used for the [pretrained RoBERTa + VLM model](https://nlp.cs.unc.edu/data/vokenization/vlm_roberta_12L_768H_wiki.zip). Is it `roberta-base` or `bert-base-uncased`?

**Comment by airsplay** [comment]
Thanks. I am using `bert-base-uncased` for  BERT + VLM (on Wiki) [here](https://github.com/airsplay/vokenization#models), and use `roberta-base` for RoBERTa + VLM (on Wiki).

**Comment by FelixLabelle** [comment]
Perfect, thanks for the quick reply!
