### ISSUE TITLE
Do vokens need when fine-tuning?

### ISSUE THREAD

**Issue by VickiCui** [airsplay/vokenization#5]
Hello，
Thank you for your great works!
I wonder if vokens are only used for pre-training? That is to say, when fine-tuning, one can directly use the pre-trained model you have released as a BERT-like model. And there is no need to do vokenization on downstream data.

**Comment by airsplay** [comment]
Yes. It does not need vokens in fine-tuning.

**Comment by VickiCui** [comment]
Thanks for your reply!
